/** Zentrale deutsche UI-Texte für Quick Check Report (App, PDF, PPTX). */
import {
  QUICK_CHECK_LABEL,
  QUICK_CHECK_PIN_LABEL,
} from '@/lib/assistant/event-quick-check/quick-check-label';

export const EQC_REPORT_COPY = {
  reportPinLabel: QUICK_CHECK_PIN_LABEL,
  sectionKpi: 'Kernkennzahlen',
  sectionWorkflow: 'Ablauf',
  sectionDomain: 'Domain & Barrierefreiheit',
  sectionDistributions: 'Verteilungen',
  sectionDistributionsHeadline: 'Anteil am Corpus',
  sectionDistributionsHint:
    'Donuts zeigen die Zusammensetzung — Rankings bleiben als Balken darüber.',
  distReadability: 'Lesbarkeit',
  distEcoGrades: 'Eco-Noten',
  distLinkMix: 'Link-Mix',
  distScoreLabel: 'Score',
  distModeLabel: 'Modus',
  distBrokenLabel: 'defekt',
  distCorpusGrade: (grade: string) => `Corpus-Note ${grade}`,
  distMedianDwell: (seconds: number) => `med. Verweildauer ${seconds}s`,
  distDominantGrade: (grade: string) => `Häufigste Note ${grade}`,
  distAvgCo2: (grams: number) => `Ø ${grams} g CO₂`,
  distLinksTotal: (total: string) => `${total} gesamt`,
  distReadabilityAria: 'Anteil Lesbarkeitsstufen',
  distEcoAria: 'Anteil Eco-Noten',
  distLinksAria: 'Interne, externe und defekte Links',
  sectionDomainScan: 'Domain-Scan',
  sectionTopIssues: 'Top-Probleme',
  sectionPersona: 'AUDION Persona',
  sectionPersonas: 'AUDION Personas',
  personaSwitcherLabel: 'Persona',
  sectionPersonaTraits: 'Eigenschaften',
  sectionGoals: 'Ziele',
  sectionPainPoints: 'Schmerzpunkte',
  sectionInterests: 'Interessen',
  personaConfidence: 'Konfidenz',
  sectionGeo: 'GEO & Wettbewerb',
  sectionGeoCheck: 'GEO-Wettbewerbsanalyse',
  sectionGeoQuestions: 'GEO-Fragen (Persona-bezogen)',
  sectionGeoMetrics: 'GEO-Kennzahlen',
  sectionGeoEeat: 'E-E-A-T',
  sectionGeoRecommendations: 'GEO-Empfehlungen',
  sectionCitations: 'Zitierungen',
  chartCitationPositions: 'Ranking pro Suchanfrage',
  chartCitationPositionsHint: 'Position in der LLM-Antwort (1 = zuerst genannt)',
  chartCompetitorScores: 'Wettbewerber-Scores',
  chartEeatScores: 'E-E-A-T im Überblick',
  chartQueryFallback: 'Frage',
  geoModelSwitcherLabel: 'LLM-Modell',
  geoModelAllLabel: 'Alle Modelle',
  geoPromptsLabel: 'Prompts',
  geoAnswerLabel: 'Antwort',
  geoCiteStackLabel: 'Cite-Stack',
  geoNoCitationsInAnswer: 'Keine Zitierungen in dieser Antwort.',
  geoCiteYouCount: 'zitieren dich',
  geoEeatGapsLabel: 'Fehlende / schwache Signale',
  geoEeatReadingLabel: 'Lesart',
  geoEeatWhyFallback:
    'Keine detaillierte Seiten-Begründung gespeichert — Scores stammen aus dem On-Page-Reading.',
  chartCitationCompetitorsHint:
    'Position pro Suchanfrage — eigene Domain und Wettbewerber (1 = zuerst genannt, leer = nicht zitiert)',
  geoOwnDomainLabel: 'Eigene Domain',
  geoLlmAnswerDialogTitle: 'LLM-Antwort',
  geoLlmAnswerExcerpt: 'Antwort-Auszug',
  geoLlmAnswerCitations: 'Genannte Domains',
  geoLlmAnswerMissing: 'Kein Antwort-Text gespeichert — nur Zitierungen verfügbar.',
  geoViewLlmAnswer: 'Antwort anzeigen',
  geoPositionNotCited: 'nicht zitiert',
  sectionInsights: 'Einschätzung & Empfehlungen',
  sectionFindings: 'Erkenntnisse',
  sectionRecommendations: 'Handlungsempfehlungen',
  sectionAppendix: 'Anhang — Rohdaten & Schritte',
  fazit: 'Fazit',
  links: 'Links',
  competitors: 'Wettbewerber',
  appendixSteps: 'Workflow-Schritte (Detail)',
  colIssue: 'Problem',
  colPages: 'Seiten',
  colDomain: 'Domain',
  colScore: 'Score',
  colQuery: 'Frage',
  colPosition: 'Position',
  colName: 'Name',
  colCount: 'Anzahl',
  colShareOfVoice: 'Sichtbarkeitsanteil',
  kpiShareOfVoice: 'Sichtbarkeitsanteil',
  kpiGeoFitness: 'GEO-Tauglichkeit',
  geoIncomplete: 'GEO-Analyse unvollständig',
  geoIncompleteTitle: 'GEO nicht vollständig',
  geoComplete: 'GEO abgeschlossen',
  noDomainScan: 'Kein Domain-Scan verfügbar.',
  noPersona: 'Keine Persona verfügbar.',
  personaChatCta: 'Mit Persona sprechen',
  personaChatOpenAudion: 'In Audion öffnen',
  unknownError: 'Unbekannter Fehler',
  noRecommendations: 'Keine Empfehlungen',
  insightPrefix: 'Erkenntnis',
  recommendationPrefix: 'Empfehlung',
  goalPrefix: 'Ziel',
  painPrefix: 'Schmerzpunkt',
  linkDashboard: 'PLEXON-Dashboard',
  linkDeepScan: 'Deep Scan in CHECKION',
  linkCheckionProject: 'CHECKION-Projekt öffnen',
  linkEchonResearch: 'ECHON Research öffnen',
  sectionDomainComparison: 'Domain-Vergleich (eigen + Wettbewerber)',
  colRole: 'Rolle',
  domainRoleOwn: 'Eigene Domain',
  domainRoleCompetitor: 'Wettbewerber',
  domainComparisonFailed: 'Fehlgeschlagene Scans',
  sectionMarket: 'Markt & Trends',
  sectionMarketFindings: 'Markt-Erkenntnisse',
  marketIncomplete: 'Markt-Research unvollständig',
  marketComplete: 'Markt-Research abgeschlossen',
  marketSkipped: 'ECHON Markt-Research nicht verfügbar',
  marketPartial: 'Markt-Research läuft noch im Hintergrund',
  pdfMarketSection: 'Markt-Überblick aus ECHON-Signalen und Waves.',
  pdfCoverEyebrow: QUICK_CHECK_LABEL,
  pdfExecutiveLead: 'Kernkennzahlen und Ablauf-Übersicht.',
  pdfDomainSection: 'Domain & Top-Probleme',
  pdfGoalsAndPain: 'Ziele & Schmerzpunkte',
  pdfInsightsSection: 'Erkenntnisse & Empfehlungen',
  pptxDomainSection: 'Domain & Barrierefreiheit',
  eeatTrust: 'Vertrauen',
  eeatExperience: 'Erfahrung',
  eeatExpertise: 'Fachkompetenz',
  eeatAuthoritativeness: 'Autorität',
} as const;

/** Deutsche Anzeigenamen für häufige AUDION-Trait-Keys. */
export const EQC_TRAIT_LABELS_DE: Record<string, string> = {
  pragmatic: 'Pragmatisch',
  analytical: 'Analytisch',
  detail_oriented: 'Detail-orientiert',
  detailoriented: 'Detail-orientiert',
  creative: 'Kreativ',
  empathetic: 'Empathisch',
  risk_averse: 'Risikobewusst',
  riskaverse: 'Risikobewusst',
  risk_tolerant: 'Risikofreudig',
  risktolerant: 'Risikofreudig',
  innovative: 'Innovationsfreudig',
  collaborative: 'Teamorientiert',
  independent: 'Selbstständig',
  data_driven: 'Datengetrieben',
  datadriven: 'Datengetrieben',
  customer_focused: 'Kundenorientiert',
  customerfocused: 'Kundenorientiert',
  skeptical: 'Skeptisch',
  cautious: 'Vorsichtig',
  patient: 'Geduldig',
  impatient: 'Ungeduldig',
  curious: 'Neugierig',
  decisive: 'Entscheidungsfreudig',
  time_pressed: 'Zeitgedrückt',
  timepressed: 'Zeitgedrückt',
  status_driven: 'Statusorientiert',
  statusdriven: 'Statusorientiert',
  systems_thinker: 'Systemdenker',
  systemsthinker: 'Systemdenker',
};

/** Schweregrade für Erkenntnisse (Anzeige). */
export const EQC_SEVERITY_LABELS_DE: Record<string, string> = {
  error: 'Kritisch',
  warning: 'Warnung',
  success: 'Positiv',
  info: 'Hinweis',
  neutral: 'Neutral',
};

export function eqcSeverityLabel(severity: string | undefined): string {
  if (!severity) return EQC_SEVERITY_LABELS_DE.info;
  return EQC_SEVERITY_LABELS_DE[severity] ?? severity;
}
