import type { UiTone } from '@/lib/assistant/ui-blocks/types';

export type ReportHighlight = {
  label: string;
  value: string | number;
  unit?: string;
  tone?: UiTone;
};

export type ReportFinding = {
  title: string;
  description: string;
  severity?: UiTone;
};

export type ReportRecommendation = {
  title: string;
  description?: string;
  priority?: number;
  category?: string;
};

/** Narrative sections generated by LLM for curated reports. */
export type ReportNarrative = {
  title: string;
  intro: string;
  executiveSummary: string;
  fazit: string;
  fazitTone?: UiTone;
  highlights?: ReportHighlight[];
  findings?: ReportFinding[];
  recommendations: ReportRecommendation[];
};

export type GeneratedReportResult = {
  reportId: string;
  title: string;
  uiLayout: import('@/lib/assistant/ui-blocks/types').UiLayout;
  narrative: ReportNarrative;
  shareToken: string;
  sharePath: string;
};
