import { StyleSheet } from '@react-pdf/renderer';
import { PDF_FONT_FAMILIES } from '@/lib/paths/pdf-fonts';
import { PDF_TYPE_LINE_HEIGHT, PDF_TYPE_WEIGHT } from '@/lib/paths/pdf-typography';
import {
  PDF_BRAND_COLOR,
  PDF_FOOTER_LOGO_GAP_PT,
  PDF_RADIUS_BUTTON_PT,
} from '@/lib/paths/pdf-print-tokens';

export const pdfColors = {
  black: '#000000',
  gray900: '#111827',
  gray700: '#374151',
  gray600: '#4B5560',
  gray500: '#6B7280',
  gray400: '#9CA3AF',
  gray200: '#E5E7EB',
  gray100: '#F3F4F6',
  white: '#FFFFFF',
  error: '#DC2626',
  warning: '#D97706',
  success: '#059669',
  brand: PDF_BRAND_COLOR,
  goalTint: 'rgba(5, 150, 105, 0.08)',
  painTint: 'rgba(217, 119, 6, 0.08)',
  accentPink: '#e91e63',
};

export const pdfStyles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: pdfColors.white,
    fontFamily: PDF_FONT_FAMILIES.body,
    fontSize: 10,
    lineHeight: PDF_TYPE_LINE_HEIGHT.body,
  },
  coverTitle: {
    fontFamily: PDF_FONT_FAMILIES.headline,
    fontSize: 34,
    fontWeight: PDF_TYPE_WEIGHT.bold,
    color: pdfColors.gray900,
    marginBottom: 8,
    letterSpacing: -1.4,
    lineHeight: PDF_TYPE_LINE_HEIGHT.tight,
  },
  coverEyebrow: {
    fontFamily: PDF_FONT_FAMILIES.body,
    fontSize: 8,
    fontWeight: PDF_TYPE_WEIGHT.light,
    color: pdfColors.gray400,
    textTransform: 'uppercase',
    letterSpacing: 1.6,
    marginBottom: 6,
    lineHeight: PDF_TYPE_LINE_HEIGHT.snug,
  },
  coverUrlBox: { marginBottom: 16 },
  coverUrl: {
    fontFamily: PDF_FONT_FAMILIES.body,
    fontSize: 11,
    fontWeight: PDF_TYPE_WEIGHT.regular,
    color: pdfColors.gray700,
    lineHeight: PDF_TYPE_LINE_HEIGHT.snug,
  },
  coverMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 20,
  },
  coverMetaItem: {
    fontSize: 8,
    fontWeight: PDF_TYPE_WEIGHT.light,
    color: pdfColors.gray400,
    lineHeight: PDF_TYPE_LINE_HEIGHT.snug,
  },
  scoreGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 8,
  },
  scoreCard: {
    width: '22%',
    minWidth: 90,
    paddingVertical: 8,
  },
  scoreCardValue: {
    fontFamily: PDF_FONT_FAMILIES.headline,
    fontSize: 17,
    fontWeight: PDF_TYPE_WEIGHT.bold,
    color: pdfColors.gray900,
    marginBottom: 2,
    lineHeight: PDF_TYPE_LINE_HEIGHT.tight,
  },
  scoreCardLabel: {
    fontFamily: PDF_FONT_FAMILIES.body,
    fontSize: 7,
    fontWeight: PDF_TYPE_WEIGHT.light,
    color: pdfColors.gray400,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    lineHeight: PDF_TYPE_LINE_HEIGHT.snug,
  },
  footer: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'flex-end',
    fontSize: 7,
    fontWeight: PDF_TYPE_WEIGHT.light,
    color: pdfColors.gray400,
    lineHeight: PDF_TYPE_LINE_HEIGHT.snug,
  },
  footerLogoGap: { width: PDF_FOOTER_LOGO_GAP_PT },
  sectionTitle: {
    fontFamily: PDF_FONT_FAMILIES.headline,
    fontSize: 12,
    fontWeight: PDF_TYPE_WEIGHT.bold,
    color: pdfColors.gray900,
    marginTop: 14,
    marginBottom: 5,
    lineHeight: PDF_TYPE_LINE_HEIGHT.tight,
    letterSpacing: -0.3,
  },
  subsectionTitle: {
    fontFamily: PDF_FONT_FAMILIES.headline,
    fontSize: 9,
    fontWeight: PDF_TYPE_WEIGHT.bold,
    color: pdfColors.gray700,
    marginTop: 6,
    marginBottom: 3,
    lineHeight: PDF_TYPE_LINE_HEIGHT.snug,
  },
  bodyText: {
    fontSize: 9,
    fontWeight: PDF_TYPE_WEIGHT.regular,
    color: pdfColors.gray700,
    marginBottom: 4,
    lineHeight: PDF_TYPE_LINE_HEIGHT.body,
  },
  metaText: {
    fontSize: 8,
    fontWeight: PDF_TYPE_WEIGHT.light,
    color: pdfColors.gray500,
    marginBottom: 3,
    lineHeight: PDF_TYPE_LINE_HEIGHT.snug,
  },
  leadText: {
    fontSize: 10,
    fontWeight: PDF_TYPE_WEIGHT.regular,
    color: pdfColors.gray700,
    lineHeight: PDF_TYPE_LINE_HEIGHT.body,
    marginBottom: 12,
  },
  sectionIntroText: {
    fontSize: 9,
    fontWeight: PDF_TYPE_WEIGHT.regular,
    color: pdfColors.gray600,
    lineHeight: PDF_TYPE_LINE_HEIGHT.body,
    marginBottom: 12,
  },
  cardBox: {
    backgroundColor: pdfColors.gray100,
    padding: 12,
    borderRadius: PDF_RADIUS_BUTTON_PT / 2,
    marginBottom: 10,
  },
  fazitCard: {
    backgroundColor: pdfColors.gray100,
    borderLeftWidth: 3,
    borderLeftColor: pdfColors.brand,
    padding: 12,
    marginBottom: 12,
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 14,
  },
  statTile: {
    width: '47%',
    paddingVertical: 6,
  },
  statTileLabel: {
    fontFamily: PDF_FONT_FAMILIES.body,
    fontSize: 7,
    fontWeight: PDF_TYPE_WEIGHT.light,
    color: pdfColors.gray400,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 4,
    lineHeight: PDF_TYPE_LINE_HEIGHT.snug,
  },
  statTileValue: {
    fontFamily: PDF_FONT_FAMILIES.headline,
    fontSize: 15,
    fontWeight: PDF_TYPE_WEIGHT.bold,
    color: pdfColors.gray900,
    lineHeight: PDF_TYPE_LINE_HEIGHT.tight,
  },
  contentPanel: {
    marginBottom: 12,
    paddingVertical: 4,
  },
  dataTableHeader: {
    flexDirection: 'row',
    paddingBottom: 6,
    marginBottom: 6,
    marginTop: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: pdfColors.gray200,
  },
  dataTableHeaderCell: {
    fontFamily: PDF_FONT_FAMILIES.body,
    fontSize: 7,
    fontWeight: PDF_TYPE_WEIGHT.light,
    color: pdfColors.gray400,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    lineHeight: PDF_TYPE_LINE_HEIGHT.snug,
  },
  dataTableRow: {
    flexDirection: 'row',
    paddingVertical: 6,
    borderBottomWidth: 0.25,
    borderBottomColor: pdfColors.gray200,
  },
  tableValue: {
    flex: 1,
    fontWeight: PDF_TYPE_WEIGHT.regular,
    color: pdfColors.gray700,
    fontSize: 9,
    lineHeight: PDF_TYPE_LINE_HEIGHT.snug,
  },
  recommendationRow: {
    marginBottom: 8,
    paddingVertical: 4,
  },
  recommendationTitle: {
    fontFamily: PDF_FONT_FAMILIES.headline,
    fontSize: 9,
    fontWeight: PDF_TYPE_WEIGHT.bold,
    color: pdfColors.gray900,
    lineHeight: PDF_TYPE_LINE_HEIGHT.snug,
    marginBottom: 3,
  },
  recommendationDesc: {
    fontSize: 8,
    fontWeight: PDF_TYPE_WEIGHT.light,
    color: pdfColors.gray600,
    lineHeight: PDF_TYPE_LINE_HEIGHT.snug,
  },
  listItemTint: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: PDF_RADIUS_BUTTON_PT / 2,
    marginBottom: 4,
  },
  statusBanner: {
    padding: 10,
    borderRadius: PDF_RADIUS_BUTTON_PT / 2,
    marginBottom: 10,
  },
});
