export { magColors, magStyles, MAG_MARGIN_X, MAG_COLUMN_MAX, MAG_PAGE_WIDTH, MAG_PAGE_HEIGHT } from './tokens'
export { MagPage } from './MagPage'
export { MagCover, type MagCoverKpi } from './MagCover'
export { MagChapter } from './MagChapter'
export { MagScoreRing } from './MagScoreRing'
export { MagDonut, type MagDonutSlice } from './MagDonut'
export { MagLedger, type MagLedgerItem } from './MagLedger'
export { MagRankedList, type MagRankedItem } from './MagRankedList'
export { MagTraitBars, type MagTrait } from './MagTraitBars'
export { MagTable } from './MagTable'
export { MagChip, MagChipRow } from './MagChip'
export { MagPersonaCard } from './MagPersonaCard'
export { MagPersonaGrid } from './MagPersonaGrid'
export { MagTwoColumn } from './MagTwoColumn'
export { MagPullQuote } from './MagPullQuote'
export { registerMagazinePdfFonts, MAG_FONT_FAMILY } from './register-mag-fonts'
