/** Deutsche UI-Texte für die standalone Quick-Check-Seite. */
import { QUICK_CHECK_LABEL } from '@/lib/assistant/event-quick-check/quick-check-label';

export const EQC_PAGE_COPY = {
  pageTitle: QUICK_CHECK_LABEL,
  pageLead:
    'Domain-Scan, AUDION-Persona und GEO-Wettbewerb in einem Durchlauf — ohne Chat, mit vollem Report-Dashboard.',
  readinessTitle: 'Produkt-APIs nicht verdrahtet',
  readinessLead:
    'Quick Check ist live in plexon-v3 — Deep Scan, Personas und GEO brauchen aber checkion-v3 und audion-v3 auf diesem Container.',
  readinessOpsHint:
    'Ops: Coolify plexon-v3 → CHECKION_API_URL + CHECKION_API_TOKEN (checkion-v3) und AUDION_API_URL + AUDION_API_TOKEN (audion-v3). Siehe knowledge/event-quick-check-staging-smoke.md.',
  urlLabel: 'Website-URL',
  urlPlaceholder: 'https://beispiel.de',
  projectNameLabel: 'Projektname (optional)',
  startButton: 'Analyse starten',
  runningTitle: 'Analyse läuft',
  runningHint: 'Aktueller Schritt — aktualisiert sich live.',
  runningRailLabel: 'Schritte',
  runningProgress: (done: number, total: number) => `${done}/${total} erledigt`,
  newCheckButton: 'Neue Analyse',
  openProjectButton: 'Zum Projekt-Dashboard',
  openCheckionProjectButton: 'In CHECKION öffnen',
  exportPdf: 'PDF herunterladen',
  exportPptx: 'PPTX herunterladen',
  errorInvalidUrl: 'Bitte eine gültige URL eingeben.',
  errorRunFailed: 'Analyse fehlgeschlagen.',
  errorLoadRun: 'Ergebnis konnte nicht geladen werden.',
  historyTitle: 'Verlauf',
  historyOpenButton: 'Verlauf',
  historyCloseButton: 'Schließen',
  historyEmpty: 'Noch keine Quick Checks — starte deine erste Analyse.',
  historyLoadError: 'Verlauf konnte nicht geladen werden.',
  historyOpenRun: 'Ergebnis öffnen',
  historyNoReport: 'Kein Report',
  historyDomainScore: 'Domain-Score',
  historySharedBadge: 'Team',
  historyOwnerLabel: (name: string) => `von ${name}`,
  shareLinkButton: 'Link teilen',
  shareLinkCopied: 'Link kopiert',
  shareLinkError: 'Link konnte nicht erstellt werden.',
  shareTeamHint: 'Sichtbar für Team im Collection-Projekt.',
  sharePublicReadOnly: 'Öffentlicher Link — nur Lesen',
  reviewTitle: 'Unternehmensprofil prüfen',
  reviewLead:
    'Kurzrecherche aus der Website. Bitte Inhalt prüfen oder anpassen — erst danach starten Scan, Persona und GEO.',
  reviewDisplayName: 'Unternehmensname',
  reviewIndustry: 'Branche / Angebot',
  reviewSummary: 'Was macht das Unternehmen?',
  reviewTargetAudience: 'Typische Zielgruppe (Käufer/Nutzer)',
  reviewDisambiguation: 'Hinweis (z. B. Name ≠ Beruf)',
  reviewConfirm: 'Profil bestätigen & Analyse fortsetzen',
  reviewConfirming: 'Analyse läuft…',
  reviewFetchWarning:
    'Website konnte nur teilweise gelesen werden — bitte Profil manuell ergänzen.',
  geoReviewTitle: 'GEO-Fragen prüfen',
  geoReviewLead:
    'Diese Fragen werden an mehrere LLMs gesendet. Bitte prüfen, ob sie zur Zielgruppe und zum Unternehmen passen — erst danach startet der GEO-Check.',
  geoReviewQuestionLabel: (index: number) => `Frage ${index + 1}`,
  geoReviewAddQuestion: 'Frage hinzufügen',
  geoReviewRemoveQuestion: 'Entfernen',
  geoReviewConfirm: 'Fragen bestätigen & GEO-Check starten',
  geoReviewConfirming: 'GEO-Check läuft…',
  geoReviewPersonaHint: 'Abgeleitet aus Persona und Unternehmensprofil.',
  geoReviewFallbackHint:
    'Abgeleitet aus Unternehmensprofil und CHECKION-Vorschlägen — ohne AUDION-Persona.',
  geoReviewMultiPersonaHint: 'Pro Persona drei Fragen — gruppiert nach Buyer-Segment.',
  geoReviewPersonaGroupLabel: (name: string, segment: string) => `${name} · ${segment}`,
  depthQuickLabel: 'Quick Check (Demo)',
  depthQuickHint: 'Schneller Demo-Scan — Anzahlen und Domaintiefe unten anpassen.',
  depthCompleteLabel: 'Komplettscan',
  depthCompleteHint:
    'Deep Scan läuft in CHECKION im Hintergrund — kann mehrere Stunden dauern. Personas & GEO können parallel geprüft werden.',
  targetGroupCountLabel: 'Zielgruppen',
  targetGroupCountHint: 'Unterschiedliche Buyer-Segmente in AUDION (1–5).',
  personaCountLabel: 'Personas',
  personaCountHint: 'Gesamtzahl Personas, verteilt auf die Zielgruppen (1–5).',
  scanMaxPagesLabel: 'Domaintiefe (Seiten)',
  scanMaxPagesHint: 'Maximale Seiten pro Domain-Scan (10–2000).',
  competitorCountLabel: 'Wettbewerber-Domains',
  competitorCountHint: (n: number) =>
    n === 0
      ? 'Nur die eigene Domain wird gescannt.'
      : `Eigene Domain + ${n} Wettbewerber = ${n + 1} Domains gesamt.`,
  competitorsReviewTitle: 'Wettbewerber prüfen',
  competitorsReviewLead:
    'CHECKION schlägt direkte Wettbewerber vor — wie im Projekt. Diese Domains werden auf dem CHECKION-Projekt gespeichert und per Deep Scan gecrawlt.',
  competitorsReviewHint: (max: number) => `Maximal ${max} Wettbewerber für den Komplettscan.`,
  competitorsReviewLabel: (index: number) => `Wettbewerber ${index + 1}`,
  competitorsReviewAddLabel: 'Domain hinzufügen',
  competitorsReviewAdd: 'Hinzufügen',
  competitorsReviewRemove: 'Entfernen',
  competitorsReviewConfirm: 'Wettbewerber bestätigen & Analyse fortsetzen',
  competitorsReviewConfirming: 'Personas & GEO werden vorbereitet…',
  deepScanWaitingTitle: 'CHECKION Deep Scan läuft',
  deepScanWaitingLead:
    'Die Deep Scans für Ihre Domain und die Wettbewerber laufen in CHECKION. Sobald alle Scans fertig sind, wird der Report automatisch erstellt.',
  deepScanWaitingHint:
    'Sie können diese Seite schließen und später über den Verlauf zurückkehren — der Scan läuft in CHECKION weiter.',
  deepScanWaitingProgressUnknown: 'Fortschritt wird geladen…',
  deepScanWaitingContinue: 'Report erstellen',
  deepScanWaitingContinuing: 'Report wird erstellt…',
  deepScanBannerTitle: 'CHECKION Deep Scan im Hintergrund',
  deepScanBannerLead:
    'Während Sie die GEO-Fragen prüfen, crawlt CHECKION Ihre Domain und die Wettbewerber — das kann mehrere Stunden dauern.',
  deepScanBannerCompleteTitle: 'CHECKION Deep Scan abgeschlossen',
  deepScanBannerCompleteLead:
    'Alle Domain-Scans sind fertig. Nach Bestätigung der GEO-Fragen wird der Report direkt erstellt.',
  geoRerunButton: 'GEO-Fragen ändern',
  geoRerunHint: 'Fragen anpassen und GEO-Check erneut ausführen — Personas und Deep Scan bleiben erhalten.',
  geoReviewCancel: 'Zurück zum Report',
  geoReviewConfirmRerun: 'Fragen bestätigen & GEO erneut starten',
} as const;
